name: Build and Release

env:
  FLUTTER_SUPPRESS_ANALYTICS: "true"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest
    name: Build iOS IPA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Adjust as needed

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS IPA
        # Ensure ExportOptions.plist exists in ios/Runner and is configured correctly.
        run: flutter build ipa --export-options-plist=ios/Runner/ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ootd-generator-ipa
          path: build/ios/ipa/*.ipa
